[package]
name = "deeprust"
version = "0.1.0"
authors = ["Vigneshwer.D <dvigneshwer@gmail.com>"]


documentation = "Machine learning crate in Rust"
repository = "https://github.com/dvigneshwer/deeprust"
readme = " Contains modules such as confusion matrix, regularizers etc for building machine learning pipeline. The crate is still under development."
keywords = ["machine learning", "deeplearning","data science","AI","prediction"]
categories = ["algorithms"]

[dependencies]

[dev-dependencies]
